SEED_PROMPTS = [
    {"prompt": "Fix the capitalization in this sentence: 'the quick brown fox jumps over the lazy dog.'", "expected_tier": "local"},
    {"prompt": "Rewrite this paragraph to sound more concise: 'We are writing to inform you that the meeting has been postponed until next Tuesday.'", "expected_tier": "local"},
    {"prompt": "Convert this title to title case: 'project roadmap for q4 launch'", "expected_tier": "local"},
    {"prompt": "Make this email more polite: 'Send me the invoice by Friday.'", "expected_tier": "local"},
    {"prompt": "Spell-check and clean up this text: 'I recived teh repot yesturday and it was realy helpful.'", "expected_tier": "local"},
    {"prompt": "Remove repeated words from this sentence: 'The team team reviewed the review notes and the notes were updated.'", "expected_tier": "local"},
    {"prompt": "Change this to active voice: 'The feature was shipped by the engineering team last week.'", "expected_tier": "local"},
    {"prompt": "Look up the definition of 'synergy' and write it in plain English.", "expected_tier": "local"},
    {"prompt": "What does 'mitigate' mean in a business context?", "expected_tier": "local"},
    {"prompt": "Turn this list into a markdown bullet list: Apple, Banana, Cherry, Date", "expected_tier": "local"},
    {"prompt": "Add a comma in the correct place: 'After lunch we will review the budget.'", "expected_tier": "local"},
    {"prompt": "Shorten this sentence without changing the meaning: 'The customer service team is currently experiencing a significant backlog of support requests.'", "expected_tier": "local"},
    {"prompt": "Create a subject line for a follow-up email about onboarding documentation.", "expected_tier": "local"},
    {"prompt": "Give me three alternatives for the opener of this summary.", "expected_tier": "local"},
    {"prompt": "Rewrite this into a more formal tone: 'We should probably talk soon about the timeline.'", "expected_tier": "local"},
    {"prompt": "What is the difference between 'affect' and 'effect'?", "expected_tier": "local"},
    {"prompt": "Format this phone number as (555) 123-4567: 5551234567", "expected_tier": "local"},
    {"prompt": "Convert this CSV line into a JSON object: name,age,city;Alice,29,Seattle", "expected_tier": "local"},
    {"prompt": "Label the parts of speech in this sentence: 'The dog barked loudly.'", "expected_tier": "local"},
    {"prompt": "Translate this slang phrase into professional English: 'We need to lock in the plan today.'", "expected_tier": "local"},
    {"prompt": "Summarize the meeting notes below in three bullets: 'Discussed launch timeline, resource constraints, QA signoff, and customer pilot schedule.'", "expected_tier": "low"},
    {"prompt": "Classify this customer feedback as positive, neutral, or negative: 'The app is fast but the login flow is confusing.'", "expected_tier": "low"},
    {"prompt": "Draft a brief product announcement for a new analytics dashboard.", "expected_tier": "low"},
    {"prompt": "Write a two-sentence summary of this incident report: 'The payment service had a brief outage after a config change, but all transactions were recovered and monitoring was improved.'", "expected_tier": "low"},
    {"prompt": "Explain the key takeaways from this release note in plain English.", "expected_tier": "low"},
    {"prompt": "Turn this feature request into a crisp Jira ticket description.", "expected_tier": "low"},
    {"prompt": "Classify these support emails into billing, technical, and account issues.", "expected_tier": "low"},
    {"prompt": "Summarize this customer interview transcript in one paragraph.", "expected_tier": "low"},
    {"prompt": "Write a 50-word executive summary of a product strategy deck.", "expected_tier": "low"},
    {"prompt": "Compare the strengths and weaknesses of using a managed database versus self-hosting.", "expected_tier": "low"},
    {"prompt": "Explain the tradeoff between caching and recomputation for a read-heavy API.", "expected_tier": "low"},
    {"prompt": "Describe the architecture of a simple event-driven notification system.", "expected_tier": "low"},
    {"prompt": "Create a short user-facing FAQ from these release notes.", "expected_tier": "low"},
    {"prompt": "Give me three ways to improve churn messaging for a SaaS product.", "expected_tier": "low"},
    {"prompt": "What are the main differences between CI and CD?", "expected_tier": "low"},
    {"prompt": "Write a concise recap of a one-hour design review discussion.", "expected_tier": "low"},
    {"prompt": "List the pros and cons of adding a dark mode to an existing web app.", "expected_tier": "low"},
    {"prompt": "Draft a polite customer response for a delayed shipment.", "expected_tier": "low"},
    {"prompt": "Explain why a team might choose a monorepo over multiple repositories.", "expected_tier": "low"},
    {"prompt": "Give a short summary of the benefits of observability for distributed services.", "expected_tier": "low"},
    {"prompt": "What is the difference between validation and sanitization in web forms?", "expected_tier": "low"},
    {"prompt": "Write a 5-point checklist for launching a small internal tool.", "expected_tier": "low"},
    {"prompt": "Generate a README section explaining the architecture of a thin Flask service for a front-end app.", "expected_tier": "low"},
    {"prompt": "Explain how to estimate the complexity of a software project during planning.", "expected_tier": "low"},
    {"prompt": "Propose three metrics to measure product adoption in a beta launch.", "expected_tier": "low"},
    {"prompt": "Create a launch email for a new feature with a friendly, concise tone.", "expected_tier": "low"},
    {"prompt": "How would you explain rate limiting to a junior engineer?", "expected_tier": "low"},
    {"prompt": "Write a short explanation of the CAP theorem for a non-expert audience.", "expected_tier": "low"},
    {"prompt": "Provide a quick comparison between PostgreSQL and MySQL for a small SaaS workload.", "expected_tier": "low"},
    {"prompt": "Choose the best naming convention for a configuration variable and explain why.", "expected_tier": "low"},
    {"prompt": "Generate a short release summary for a mobile app update.", "expected_tier": "low"},
    {"prompt": "Explain the difference between a queue and a topic in a messaging system.", "expected_tier": "low"},
    {"prompt": "Write a brief onboarding checklist for a new engineer joining a product team.", "expected_tier": "low"},
    {"prompt": "Generate a minimal API contract for a user profile endpoint.", "expected_tier": "low"},
    {"prompt": "Find the bug in this Python function and explain how to fix it:\n\ndef total(items):\n    sum = 0\n    for item in items:\n        sum += item\n    return sum\n", "expected_tier": "medium"},
    {"prompt": "Refactor this Ruby method to be cleaner and easier to test without changing behavior.", "expected_tier": "medium"},
    {"prompt": "Write a Python function to parse a CSV file and return a list of dictionaries.", "expected_tier": "medium"},
    {"prompt": "Given this SQL schema, write a query to find customers who placed orders in the last 30 days.", "expected_tier": "medium"},
    {"prompt": "Debug this JavaScript bug: a button click does nothing even though the event handler is attached.", "expected_tier": "medium"},
    {"prompt": "Explain how to refactor this nested if/else block into a cleaner design.", "expected_tier": "medium"},
    {"prompt": "Write a regex that matches valid U.S. ZIP codes and explain each part.", "expected_tier": "medium"},
    {"prompt": "Design a small database schema for storing user subscriptions and billing events.", "expected_tier": "medium"},
    {"prompt": "Create a unit test for a function that calculates compound interest.", "expected_tier": "medium"},
    {"prompt": "Explain how to add pagination to this REST endpoint without breaking existing clients.", "expected_tier": "medium"},
    {"prompt": "Refactor this code to avoid duplication while keeping the public API stable.", "expected_tier": "medium"},
    {"prompt": "Write a Bash script to archive logs older than 30 days and keep the newest 10 files.", "expected_tier": "medium"},
    {"prompt": "Reason through the failure mode of this async job queue and propose a fix.", "expected_tier": "medium"},
    {"prompt": "Compare two ways to cache API results and suggest which is safer under a traffic spike.", "expected_tier": "medium"},
    {"prompt": "Create a simple design for a rate-limited API gateway with retries and backoff.", "expected_tier": "medium"},
    {"prompt": "Explain why this recursive function causes a stack overflow and show a safer version.", "expected_tier": "medium"},
    {"prompt": "Write a Python function to retry a flaky network call with exponential backoff.", "expected_tier": "medium"},
    {"prompt": "Build a small service contract for user sign-up with validation and error messages.", "expected_tier": "medium"},
    {"prompt": "Debug a race condition in a multithreaded counter and propose a fix.", "expected_tier": "medium"},
    {"prompt": "Explain the root cause of this deadlock in a database transaction and how to prevent it.", "expected_tier": "medium"},
    {"prompt": "Refactor an overgrown function into smaller composable steps while preserving semantics.", "expected_tier": "medium"},
    {"prompt": "Design a schema for storing audit logs, user actions, and permissions revisions.", "expected_tier": "medium"},
    {"prompt": "Write a migration plan to move a service from synchronous HTTP calls to an async job system.", "expected_tier": "medium"},
    {"prompt": "Prove that this algorithm runs in O(n log n) and explain the tradeoff with memory use.", "expected_tier": "high"},
    {"prompt": "Analyze a system with a growing backlog and propose an architecture that reduces latency without breaking correctness.", "expected_tier": "high"},
    {"prompt": "Debug a multi-file Python app where a subtle data race causes intermittent failures under load.", "expected_tier": "high"},
    {"prompt": "Refactor this legacy monolith to isolate the payment domain without a risky rewrite.", "expected_tier": "high"},
    {"prompt": "Explain the root cause of an authentication bug that only appears when users switch regions on mobile devices.", "expected_tier": "high"},
    {"prompt": "Analyze the tradeoffs of a service mesh for a small team running 12 microservices.", "expected_tier": "high"},
    {"prompt": "Design a migration path from a centralized relational database to a partitioned event-driven architecture.", "expected_tier": "high"},
    {"prompt": "Give a high-confidence diagnosis for a production outage caused by a connection pool saturation pattern.", "expected_tier": "high"},
    {"prompt": "Identify the likely correctness issue in a distributed system that fails only under clock skew.", "expected_tier": "high"},
    {"prompt": "Refactor a large service boundary to reduce coupling while preserving compatibility for existing clients.", "expected_tier": "high"},
    {"prompt": "Compare three deployment strategies for a latency-sensitive system and explain which one best addresses tail latency.", "expected_tier": "high"},
    {"prompt": "Debug a failing CI pipeline caused by flaky end-to-end tests across multiple environments.", "expected_tier": "high"},
    {"prompt": "Analyze a data pipeline where duplicate records appear only during batch backfills and propose a fix.", "expected_tier": "high"},
    {"prompt": "Explain how to reason about eventual consistency when a downstream dependency occasionally returns stale data.", "expected_tier": "high"},
    {"prompt": "Design a safe rollout plan for a schema change affecting millions of records.", "expected_tier": "high"},
    {"prompt": "Trace the failure chain in a distributed transaction that leaves partial writes and inconsistent inventory counts.", "expected_tier": "high"},
    {"prompt": "Propose a long-term architecture for a system with growing data volume, high availability requirements, and strict correctness guarantees.", "expected_tier": "high"},
    {"prompt": "Explain why a caching strategy that looks correct for a single node fails under sharded traffic patterns.", "expected_tier": "high"},
    {"prompt": "Debug a cross-service auth bug where tokens work in staging but fail in production for one region.", "expected_tier": "high"},
    {"prompt": "Recommend a modernization strategy for a brittle monolith with no test coverage around payment logic.", "expected_tier": "high"},
    {"prompt": "Write a detailed migration plan for moving a team from a single PostgreSQL database to a multi-region architecture.", "expected_tier": "high"},
    {"prompt": "Analyze the correctness of a concurrency model that uses optimistic locking and stale reads.", "expected_tier": "high"},
    {"prompt": "Give a root-cause analysis for an intermittent production bug that appears only when a background job runs during peak traffic.", "expected_tier": "high"},
    {"prompt": "Reformat this sentence for grammar and punctuation: 'if you can send the report by friday please do so and also please confirm receipt'", "expected_tier": "local"},
    {"prompt": "Normalize this JSON blob and make it readable: {'name':'Alice','age':29,'city':'Seattle'}", "expected_tier": "local"},
    {"prompt": "Translate this note into a professional status update: 'We hit a blocker on the auth flow but we think we'll solve it soon.'", "expected_tier": "local"},
    {"prompt": "Look up the meaning of 'ubiquitous' and give a one-line explanation.", "expected_tier": "local"},
    {"prompt": "Check whether this sentence is grammatical: 'Neither of the developers were available for the meeting.'", "expected_tier": "local"},
    {"prompt": "Correct the ordering of words in this sentence: 'Only yesterday the client approved the contract.'", "expected_tier": "local"},
    {"prompt": "Write a subject line for an email asking for a product demo.", "expected_tier": "local"},
    {"prompt": "Rephrase this note to sound friendlier: 'Please review this before the end of day.'", "expected_tier": "local"},
    {"prompt": "Turn this into a numbered list: 'Plan kickoff, requirements review, design approval, implementation, QA'", "expected_tier": "local"},
    {"prompt": "Summarize this customer review in one sentence: 'The onboarding was smooth, the UI looks great, but the export flow is frustrating.'", "expected_tier": "low"},
    {"prompt": "Describe the likely user intent behind this support message: 'I can't find where to update my billing info.'", "expected_tier": "low"},
    {"prompt": "Draft a release note for a bug fix that improved login performance.", "expected_tier": "low"},
    {"prompt": "Write a short progress update for a product team after a sprint demo.", "expected_tier": "low"},
    {"prompt": "Classify the risk level of this issue: 'The retention metric dropped 12% after a pricing experiment.'", "expected_tier": "low"},
    {"prompt": "Explain what a webhook is in simple business terms.", "expected_tier": "low"},
    {"prompt": "Write a concise summary of a customer advisory board meeting.", "expected_tier": "low"},
    {"prompt": "Create a PR description for a small bug fix in the checkout flow.", "expected_tier": "low"},
    {"prompt": "Assess whether this statement is an opinion or a fact: 'The new onboarding flow is easier to understand.'", "expected_tier": "low"},
    {"prompt": "Write a public-facing changelog note for a security update.", "expected_tier": "low"},
    {"prompt": "Generate a sample acceptance criteria list for a search filter feature.", "expected_tier": "low"},
    {"prompt": "Explain the implications of enabling two-factor authentication for a small team.", "expected_tier": "low"},
    {"prompt": "Recommend a schema for storing product variants with pricing and inventory.", "expected_tier": "medium"},
    {"prompt": "Write a function that collapses consecutive whitespace in a string while preserving newlines.", "expected_tier": "medium"},
    {"prompt": "Debug a Flask route that returns HTML instead of JSON when an exception is thrown.", "expected_tier": "medium"},
    {"prompt": "Explain how to design a test around a flaky integration that depends on an external API.", "expected_tier": "medium"},
    {"prompt": "Write a SQL query to find duplicate emails in a users table.", "expected_tier": "medium"},
    {"prompt": "Refactor a long function that handles validation, normalization, and persistence into smaller steps.", "expected_tier": "medium"},
    {"prompt": "Propose a safe retry policy for a payment processor with transient 429s.", "expected_tier": "medium"},
    {"prompt": "Describe the steps for incremental migration from a single-user SQLite DB to a shared Postgres service.", "expected_tier": "medium"},
    {"prompt": "Determine how to fix a bug where a pagination cursor is invalid after row deletion.", "expected_tier": "medium"},
    {"prompt": "Write a minimal API contract for a search endpoint with pagination and filters.", "expected_tier": "medium"},
    {"prompt": "Trace the likely cause of a memory leak in a background worker that collects metrics every second.", "expected_tier": "high"},
    {"prompt": "Diagnose the underlying issue behind a feature flag that causes production diffs only when multiple services deploy together.", "expected_tier": "high"},
    {"prompt": "Propose a safe rollback plan for a database migration affecting customer orders.", "expected_tier": "high"},
    {"prompt": "Analyze the failure mode in a distributed queue where messages are duplicated under load.", "expected_tier": "high"},
    {"prompt": "Explain why this dependency upgrade caused a silent correctness regression in an edge-case branch.", "expected_tier": "high"},
    {"prompt": "Design a plan to isolate a payment service from a legacy monolith without downtime.", "expected_tier": "high"},
    {"prompt": "Debug a cross-region cache inconsistency bug in a read-heavy product catalog.", "expected_tier": "high"},
    {"prompt": "Trace the root cause of a production incident involving stale user sessions after a token rotation rollout.", "expected_tier": "high"},
    {"prompt": "Explain why a feature appears correct in unit tests but fails in production under real concurrency.", "expected_tier": "high"},
    {"prompt": "Evaluate the architecture tradeoffs for moving from a shared services model to independently deployable domains.", "expected_tier": "high"},
]
